version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  build-and-test:
    executor:
      name: node/default
      # working_directory: ~/demo

    steps:
      - checkout
      - run: npm install
      #- run: npm test
      # - run: npm install -D sonarqube-scanner
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0

workflows:
    build-and-test:
      jobs:
        - build-and-test:
            context: sonarcloud
