version: 2
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0

jobs:
  build:
    docker:
        - image: circleci/node:10.16.3
    steps:
      ## Fetch all release tags
      - checkout
      - run:
          name: Install Node.js dependencies with Npm
          command: npm install
      - sonarcloud/scan 

  
workflows:
  version: 2
  build_and_test_publish:
    jobs:
       - build:
            context: sonarcloud
