version: 2

jobs:
  build:
    docker:
        - image: circleci/node:10.16.3
    steps:
      ## Fetch all release tags
      - checkout
      - run:
          name: Install Node.js dependencies with Npm
          command: npm install
      - run:
          name: Test
          command: CI=true npm run coverage
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0
  
workflows:
version: 2
    build-and-test:
      jobs:
        - build-and-test:
            context: sonarcloud
