version: 2.1
orbs:
  sonarcloud: sonarsource/sonarcloud@1.0.0
jobs:
  build:
    docker:
      - image: circleci/node:10.16.3
    steps:
    - checkout
    - sonarcloud/scan
    - run:
          name: Run Sonarqube scanner
          command: |
                
                -Dsonar.host.url=https://sonarcloud.io/ \
                -Dsonar.projectKey=Main-project-key \
                -Dsonar.organization=vsawanny
               



workflows:
  my-workflow:
    jobs:
      - build:
          context: sonarcloud



          












          
